### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by luke-m** [drcmda/use-cannon#1]
The demo that is linked in the README is broken:

![image](https://user-images.githubusercontent.com/16318844/75783990-c1089f00-5d61-11ea-9381-d94fd81ee4f2.png)

Taken here: https://codesandbox.io/s/r3f-cannon-instanced-physics-g1s88

**Comment by drcmda** [comment]
seems to run, error seems to be threejs related. do other threejs demos run on your computer?

**Comment by luke-m** [comment]
Seems to be a problem with codesandbox and the browser I'm using (brave) which has a very strong privacy/security blocking behaviour.
